# Generated by Django 5.2.8 on 2024-05-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0008_alter_match_scraped_at_alter_match_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressBetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=20)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('express_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='matches.expressbet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
