# Generated by Django 5.2.8 on 2024-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True, default="")),
            ],
            options={
                'verbose_name_plural': 'Scraper Status',
            },
        ),
    ]
